jobscript: "workflow/profiles/slurm/slurm-jobscript.sh"
cluster: "workflow/profiles/slurm/slurm-submit.py"
cluster-status: "workflow/profiles/slurm/slurm-status.py"
snakefile: "workflow/Snakefile"
jobs: 4096
rerun-incomplete: true
keep-going: true
latency-wait: 60

